extensions:
    pim-association-type-create-modal:
        module: pim/form/common/creation/modal
        config:
            labels:
                title: pim_common.create
                subTitle: pim_menu.item.association_type
            picture: illustrations/Association-types.svg
            successMessage: pim_enrich.entity.association_type.flash.create.success
            editRoute: pim_enrich_associationtype_edit
            postUrl: pim_enrich_associationtype_rest_create
            routerKey: code

    pim-association-type-create-form:
        module: pim/form/common/creation/field
        parent: pim-association-type-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: code
            label: pim_common.code

    pim-association-type-properties-bidirectional:
        module: pim/form/common/fields/boolean
        parent: pim-association-type-create-modal
        targetZone: fields
        position: 20
        config:
            fieldName: isBidirectional
            label: pim_enrich.entity.association_type.property.is_bidirectional
            defaultValue: false
